sudo: required
language: bash
services:
- docker

script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

- docker build -f ./Dockerfile -t vladshub/couchpotato-rutracker:latest .
- docker push vladshub/couchpotato-rutracker:latest

